### ISSUE TITLE
vendor folder missing

### ISSUE THREAD

**Issue by HarshalShende** [justinhartman/complete-php7-ecom-website#2]
### Describe the Bug

_A clear and concise description of what the bug is._

### To Reproduce

_Steps to reproduce the behaviour:_

  1. Click on '...'
  1. Scroll down to '...'
  1. See error

### Expected behaviour

_A clear and concise description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

![Example Screenshot][screenshot-1]

### Specifications

**Desktop (please complete the following information):**

  - Hardware: [e.g. MacBook Pro (13-inch, Mid 2012)] 
  - OS: [e.g. macOS 10.13.4]
  - Browser: [e.g. Chrome, Safari, IE]
  - Version: [e.g. 61, 11.1, 9]

**Smartphone (please complete the following information):**

  - Device: [e.g. iPhoneX]
  - OS: [e.g. iOS11.1]
  - Browser: [e.g. stock browser, safari]
  - Version: [e.g. 22]

### Additional Context

_Add any other context about the problem here._

[//]: # (Add links to any screenshots or other relevant information below)

[screenshot-1]: https://ws3.sinaimg.cn/large/006tKfTcly1fr6kihddwhj30b008j74g.jpg

**Comment by justinhartman** [comment]
You need to run: `$ composer install` from the command line to install all the project dependencies. Until you run this, nothing will work.
