### ISSUE TITLE
BUG ISSUE

### ISSUE THREAD

**Issue by Bayohturay** [justinhartman/complete-php7-ecom-website#3]
### Describe the Bug

_Fatal error: require(): Failed opening required 'C:\xampp\htdocs\ECOMMERCE\vendor\autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ECOMMERCE\config\bootstrap.php on line 34
This is the above error that display in the browser when i run it locally.It tells me that autoload.php
is required in bootstrap.php in confing folder._

### To Reproduce

_Steps to reproduce the behaviour:_

  1. Click on '...'
  1. Scroll down to '...'
  1. See error

### Expected behaviour

_To resolve the error and give me access to the page in the browser._

### Screenshots

_If applicable, add screenshots to help explain your problem._

![Example Screenshot][screenshot-1]

### Specifications

**Desktop (please complete the following information):**

  - Hardware: HP Elite Book pro i7 2.7GHz
  - OS: Windows 10
  - Browser: Chrome
  - Version: 11

**Smartphone (please complete the following information):**

  - Device: Android
  - OS: [e.g. Android 8.1
  - Browser: Chrome
  - Version: [e.g. 22]
![error](https://user-images.githubusercontent.com/44406717/77812495-e5a11f80-705e-11ea-8b83-8135567e4f9b.PNG)
![error](https://user-images.githubusercontent.com/44406717/77812499-ee91f100-705e-11ea-82e1-d1e220d3774a.PNG)

### Additional Context

_Add any other context about the problem here._

[//]: # (Add links to any screenshots or other relevant information below)

[screenshot-1]: https://ws3.sinaimg.cn/large/006tKfTcly1fr6kihddwhj30b008j74g.jpg

**Comment by justinhartman** [comment]
You need to run: `composer install` from a terminal to install all the project dependencies. Until you run this, nothing will work. Composer downloads the depencencies and then creates the vendor and autoload functions.

I see you are using `xampp`. This means you won't have composer installed but you can [follow this tutorial](https://www.bladephp.co/install-composer-on-windows-with-xampp) to show you how to install it.

Once you have composer installed you need to run the `composer install` command.
