### ISSUE TITLE
error while installing 

### ISSUE THREAD

**Issue by meetmec12** [justinhartman/complete-php7-ecom-website#4]
### Describe the Bug
While installing on local machine i get couple of  failed to open stream error 
_A clear and concise description of what the bug is._
Warning: require(C:\xampp\htdocs\ecom\vendor\autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\ecom\config\bootstrap.php on line 34

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\ecom\vendor\autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ecom\config\bootstrap.php on line 34

i also tried composer install , but i get this error :
Deprecation warning: Your package name complete-php7-ecom-website is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

### To Reproduce

_Steps to reproduce the behaviour:_

  1. Click on '...'
  1. Scroll down to '...'
  1. See error

### Expected behaviour

_A clear and concise description of what you expected to happen._

### Screenshots

_If applicable, add screenshots to help explain your problem._

![Example Screenshot][screenshot-1]

### Specifications

**Desktop (please complete the following information):**

  - Hardware: [e.g. MacBook Pro (13-inch, Mid 2012)] 
  - OS: [e.g. macOS 10.13.4]
  - Browser: [e.g. Chrome, Safari, IE]
  - Version: [e.g. 61, 11.1, 9]

**Smartphone (please complete the following information):**

  - Device: [e.g. iPhoneX]
  - OS: [e.g. iOS11.1]
  - Browser: [e.g. stock browser, safari]
  - Version: [e.g. 22]

### Additional Context

_Add any other context about the problem here._

[//]: # (Add links to any screenshots or other relevant information below)

[screenshot-1]: https://ws3.sinaimg.cn/large/006tKfTcly1fr6kihddwhj30b008j74g.jpg

**Comment by justinhartman** [comment]
@meetmec12 thank you for pointing this out. Commit 14ad557 resolves your issues. I have also included some installation instructions to help you out. Go to [this section of the README](https://github.com/justinhartman/complete-php7-ecom-website#installing) and you will see how to install the project. 

Please be sure to update your code to the latest version using `git pull origin master` so you get the latest fixes. You will then be able to run `composer install` and setup the site accordingly. Just follow the steps outlined in the README.

**Comment by justinhartman** [comment]
@meetmec12 If you find this project valuable, please consider [giving a small donation](https://paypal.me/22digital) to help keep the project alive.
